//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 02:48:30 PM MST 
//


package semanticMarkup.io.input.lib.taxonx;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="provider">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessPoint" type="{http://digir.net/schema/protocol/2003/1.0}urlType"/>
 *                   &lt;element name="implementation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="host">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
 *                             &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="resource" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
 *                             &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="useRestrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="conceptualSchema" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="schemaLocation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="recordIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="recordBasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="numberOfRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="dateLastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="minQueryTermLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="maxSearchResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="maxInventoryResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "provider"
})
@XmlRootElement(name = "metadata", namespace = "http://digir.net/schema/protocol/2003/1.0")
public class Metadata {

    @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
    protected Metadata.Provider provider;

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata.Provider }
     *     
     */
    public Metadata.Provider getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata.Provider }
     *     
     */
    public void setProvider(Metadata.Provider value) {
        this.provider = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessPoint" type="{http://digir.net/schema/protocol/2003/1.0}urlType"/>
     *         &lt;element name="implementation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="host">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
     *                   &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="resource" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
     *                   &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="useRestrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="conceptualSchema" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="schemaLocation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="recordIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="recordBasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="numberOfRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="dateLastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="minQueryTermLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                   &lt;element name="maxSearchResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                   &lt;element name="maxInventoryResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "accessPoint",
        "implementation",
        "host",
        "resource"
    })
    public static class Provider {

        @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
        protected String name;
        @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
        protected String accessPoint;
        @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
        protected String implementation;
        @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
        protected Metadata.Provider.Host host;
        @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
        protected List<Metadata.Provider.Resource> resource;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the accessPoint property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessPoint() {
            return accessPoint;
        }

        /**
         * Sets the value of the accessPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessPoint(String value) {
            this.accessPoint = value;
        }

        /**
         * Gets the value of the implementation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImplementation() {
            return implementation;
        }

        /**
         * Sets the value of the implementation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplementation(String value) {
            this.implementation = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link Metadata.Provider.Host }
         *     
         */
        public Metadata.Provider.Host getHost() {
            return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link Metadata.Provider.Host }
         *     
         */
        public void setHost(Metadata.Provider.Host value) {
            this.host = value;
        }

        /**
         * Gets the value of the resource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Metadata.Provider.Resource }
         * 
         * 
         */
        public List<Metadata.Provider.Resource> getResource() {
            if (resource == null) {
                resource = new ArrayList<Metadata.Provider.Resource>();
            }
            return this.resource;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
         *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "code",
            "relatedInformation",
            "contact",
            "_abstract"
        })
        public static class Host {

            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected String name;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected String code;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected List<String> relatedInformation;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected List<Contact> contact;
            @XmlElement(name = "abstract", namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String _abstract;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the relatedInformation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the relatedInformation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRelatedInformation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getRelatedInformation() {
                if (relatedInformation == null) {
                    relatedInformation = new ArrayList<String>();
                }
                return this.relatedInformation;
            }

            /**
             * Gets the value of the contact property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the contact property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContact().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Contact }
             * 
             * 
             */
            public List<Contact> getContact() {
                if (contact == null) {
                    contact = new ArrayList<Contact>();
                }
                return this.contact;
            }

            /**
             * Gets the value of the abstract property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbstract() {
                return _abstract;
            }

            /**
             * Sets the value of the abstract property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbstract(String value) {
                this._abstract = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="relatedInformation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="contact" type="{http://digir.net/schema/protocol/2003/1.0}contact" maxOccurs="unbounded"/>
         *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="useRestrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="conceptualSchema" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="schemaLocation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="recordIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="recordBasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="numberOfRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="dateLastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="minQueryTermLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *         &lt;element name="maxSearchResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *         &lt;element name="maxInventoryResponseRecords" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "code",
            "relatedInformation",
            "contact",
            "_abstract",
            "keywords",
            "citation",
            "useRestrictions",
            "conceptualSchema",
            "recordIdentifier",
            "recordBasis",
            "numberOfRecords",
            "dateLastUpdated",
            "minQueryTermLength",
            "maxSearchResponseRecords",
            "maxInventoryResponseRecords"
        })
        public static class Resource {

            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected String name;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected String code;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected List<String> relatedInformation;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected List<Contact> contact;
            @XmlElement(name = "abstract", namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String _abstract;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String keywords;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String citation;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String useRestrictions;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected List<Metadata.Provider.Resource.ConceptualSchema> conceptualSchema;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            protected String recordIdentifier;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            protected String recordBasis;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger numberOfRecords;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar dateLastUpdated;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger minQueryTermLength;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger maxSearchResponseRecords;
            @XmlElement(namespace = "http://digir.net/schema/protocol/2003/1.0")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger maxInventoryResponseRecords;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the relatedInformation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the relatedInformation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRelatedInformation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getRelatedInformation() {
                if (relatedInformation == null) {
                    relatedInformation = new ArrayList<String>();
                }
                return this.relatedInformation;
            }

            /**
             * Gets the value of the contact property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the contact property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContact().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Contact }
             * 
             * 
             */
            public List<Contact> getContact() {
                if (contact == null) {
                    contact = new ArrayList<Contact>();
                }
                return this.contact;
            }

            /**
             * Gets the value of the abstract property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbstract() {
                return _abstract;
            }

            /**
             * Sets the value of the abstract property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbstract(String value) {
                this._abstract = value;
            }

            /**
             * Gets the value of the keywords property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKeywords() {
                return keywords;
            }

            /**
             * Sets the value of the keywords property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKeywords(String value) {
                this.keywords = value;
            }

            /**
             * Gets the value of the citation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCitation() {
                return citation;
            }

            /**
             * Sets the value of the citation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCitation(String value) {
                this.citation = value;
            }

            /**
             * Gets the value of the useRestrictions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseRestrictions() {
                return useRestrictions;
            }

            /**
             * Sets the value of the useRestrictions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseRestrictions(String value) {
                this.useRestrictions = value;
            }

            /**
             * Gets the value of the conceptualSchema property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the conceptualSchema property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getConceptualSchema().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Metadata.Provider.Resource.ConceptualSchema }
             * 
             * 
             */
            public List<Metadata.Provider.Resource.ConceptualSchema> getConceptualSchema() {
                if (conceptualSchema == null) {
                    conceptualSchema = new ArrayList<Metadata.Provider.Resource.ConceptualSchema>();
                }
                return this.conceptualSchema;
            }

            /**
             * Gets the value of the recordIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordIdentifier() {
                return recordIdentifier;
            }

            /**
             * Sets the value of the recordIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordIdentifier(String value) {
                this.recordIdentifier = value;
            }

            /**
             * Gets the value of the recordBasis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordBasis() {
                return recordBasis;
            }

            /**
             * Sets the value of the recordBasis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordBasis(String value) {
                this.recordBasis = value;
            }

            /**
             * Gets the value of the numberOfRecords property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberOfRecords() {
                return numberOfRecords;
            }

            /**
             * Sets the value of the numberOfRecords property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberOfRecords(BigInteger value) {
                this.numberOfRecords = value;
            }

            /**
             * Gets the value of the dateLastUpdated property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateLastUpdated() {
                return dateLastUpdated;
            }

            /**
             * Sets the value of the dateLastUpdated property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateLastUpdated(XMLGregorianCalendar value) {
                this.dateLastUpdated = value;
            }

            /**
             * Gets the value of the minQueryTermLength property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMinQueryTermLength() {
                return minQueryTermLength;
            }

            /**
             * Sets the value of the minQueryTermLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMinQueryTermLength(BigInteger value) {
                this.minQueryTermLength = value;
            }

            /**
             * Gets the value of the maxSearchResponseRecords property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxSearchResponseRecords() {
                return maxSearchResponseRecords;
            }

            /**
             * Sets the value of the maxSearchResponseRecords property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxSearchResponseRecords(BigInteger value) {
                this.maxSearchResponseRecords = value;
            }

            /**
             * Gets the value of the maxInventoryResponseRecords property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxInventoryResponseRecords() {
                return maxInventoryResponseRecords;
            }

            /**
             * Sets the value of the maxInventoryResponseRecords property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxInventoryResponseRecords(BigInteger value) {
                this.maxInventoryResponseRecords = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="schemaLocation" type="{http://digir.net/schema/protocol/2003/1.0}urlType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ConceptualSchema {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "schemaLocation")
                protected String schemaLocation;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the schemaLocation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSchemaLocation() {
                    return schemaLocation;
                }

                /**
                 * Sets the value of the schemaLocation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSchemaLocation(String value) {
                    this.schemaLocation = value;
                }

            }

        }

    }

}
