//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 02:48:30 PM MST 
//


package semanticMarkup.io.input.lib.taxonx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * An abstract type provided as a base from which to derive all multi-element comparitive operator types.
 * 
 * <p>Java class for MultiCOP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiCOP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://digir.net/schema/protocol/2003/1.0}COP">
 *       &lt;sequence>
 *         &lt;element name="list" type="{http://digir.net/schema/protocol/2003/1.0}listType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiCOP", namespace = "http://digir.net/schema/protocol/2003/1.0")
@XmlSeeAlso({
    In.class
})
public abstract class MultiCOP
    extends COP
{


}
