//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 02:48:30 PM MST 
//


package semanticMarkup.io.input.lib.taxonx;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for p complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="p">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="collection_event" type="{http://www.taxonx.org/schema/v1}collection_event"/>
 *         &lt;element name="locality" type="{http://www.taxonx.org/schema/v1}locality"/>
 *         &lt;element name="xmldata" type="{http://www.taxonx.org/schema/v1}xmldata"/>
 *         &lt;element name="character" type="{http://www.taxonx.org/schema/v1}character"/>
 *         &lt;element name="name" type="{http://www.taxonx.org/schema/v1}name"/>
 *         &lt;element name="figure" type="{http://www.taxonx.org/schema/v1}figure"/>
 *         &lt;element name="note" type="{http://www.taxonx.org/schema/v1}note"/>
 *         &lt;element name="pb" type="{http://www.taxonx.org/schema/v1}pb"/>
 *         &lt;element name="seg" type="{http://www.taxonx.org/schema/v1}seg"/>
 *         &lt;element name="nomenclature" type="{http://www.taxonx.org/schema/v1}nomenclature"/>
 *         &lt;element name="bibref" type="{http://www.taxonx.org/schema/v1}bibref"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.taxonx.org/schema/v1}standardAttrs"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "p", namespace = "http://www.taxonx.org/schema/v1", propOrder = {
    "content"
})
public class P {

    @XmlElementRefs({
        @XmlElementRef(name = "note", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nomenclature", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seg", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "name", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "locality", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "character", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pb", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collection_event", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "xmldata", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bibref", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "figure", namespace = "http://www.taxonx.org/schema/v1", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "n")
    protected String n;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Note }{@code >}
     * {@link JAXBElement }{@code <}{@link Nomenclature }{@code >}
     * {@link JAXBElement }{@code <}{@link Seg }{@code >}
     * {@link JAXBElement }{@code <}{@link Name }{@code >}
     * {@link JAXBElement }{@code <}{@link Locality }{@code >}
     * {@link JAXBElement }{@code <}{@link Character }{@code >}
     * {@link JAXBElement }{@code <}{@link Pb }{@code >}
     * {@link JAXBElement }{@code <}{@link CollectionEvent }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Xmldata }{@code >}
     * {@link JAXBElement }{@code <}{@link Figure }{@code >}
     * {@link JAXBElement }{@code <}{@link Bibref }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN(String value) {
        this.n = value;
    }

}
