//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 02:48:30 PM MST 
//


package semanticMarkup.io.input.lib.taxonx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="resourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="cartographic"/>
 *     &lt;enumeration value="notated music"/>
 *     &lt;enumeration value="sound recording-musical"/>
 *     &lt;enumeration value="sound recording-nonmusical"/>
 *     &lt;enumeration value="sound recording"/>
 *     &lt;enumeration value="still image"/>
 *     &lt;enumeration value="moving image"/>
 *     &lt;enumeration value="three dimensional object"/>
 *     &lt;enumeration value="software, multimedia"/>
 *     &lt;enumeration value="mixed material"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "resourceType")
@XmlEnum
public enum ResourceType {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("cartographic")
    CARTOGRAPHIC("cartographic"),
    @XmlEnumValue("notated music")
    NOTATED_MUSIC("notated music"),
    @XmlEnumValue("sound recording-musical")
    SOUND_RECORDING_MUSICAL("sound recording-musical"),
    @XmlEnumValue("sound recording-nonmusical")
    SOUND_RECORDING_NONMUSICAL("sound recording-nonmusical"),

    /**
     * Use for mixed musical and nonmusical, or when not specified whether musical or nonmusical.
     * 
     * 
     */
    @XmlEnumValue("sound recording")
    SOUND_RECORDING("sound recording"),
    @XmlEnumValue("still image")
    STILL_IMAGE("still image"),
    @XmlEnumValue("moving image")
    MOVING_IMAGE("moving image"),
    @XmlEnumValue("three dimensional object")
    THREE_DIMENSIONAL_OBJECT("three dimensional object"),
    @XmlEnumValue("software, multimedia")
    SOFTWARE_MULTIMEDIA("software, multimedia"),
    @XmlEnumValue("mixed material")
    MIXED_MATERIAL("mixed material");
    private final String value;

    ResourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResourceType fromValue(String v) {
        for (ResourceType c: ResourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
