//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 02:48:30 PM MST 
//


package semanticMarkup.io.input.lib.taxonx;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxonxHeader" type="{http://www.taxonx.org/schema/v1}taxonxHeader" minOccurs="0"/>
 *         &lt;element name="head" type="{http://www.taxonx.org/schema/v1}head" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="nomenclature" type="{http://www.taxonx.org/schema/v1}nomenclature"/>
 *           &lt;element name="div" type="{http://www.taxonx.org/schema/v1}div"/>
 *           &lt;element name="ref_group" type="{http://www.taxonx.org/schema/v1}ref_group"/>
 *           &lt;element name="pb" type="{http://www.taxonx.org/schema/v1}pb"/>
 *           &lt;element name="figure" type="{http://www.taxonx.org/schema/v1}figure"/>
 *           &lt;element ref="{http://www.taxonx.org/schema/v1}treatment"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.taxonx.org/schema/v1}standardAttrs"/>
 *       &lt;attribute name="rank">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="order"/>
 *             &lt;enumeration value="family"/>
 *             &lt;enumeration value="species"/>
 *             &lt;enumeration value="genus"/>
 *             &lt;enumeration value="subspecies"/>
 *             &lt;enumeration value="superfamily"/>
 *             &lt;enumeration value="suborder"/>
 *             &lt;enumeration value="subfamily"/>
 *             &lt;enumeration value="infrasubspecific"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="other_rank" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxonxHeader",
    "head",
    "nomenclatureOrDivOrRefGroup"
})
@XmlRootElement(name = "treatment", namespace = "http://www.taxonx.org/schema/v1")
public class Treatment {

    @XmlElement(namespace = "http://www.taxonx.org/schema/v1")
    protected TaxonxHeader taxonxHeader;
    @XmlElement(namespace = "http://www.taxonx.org/schema/v1")
    protected Head head;
    @XmlElements({
        @XmlElement(name = "nomenclature", namespace = "http://www.taxonx.org/schema/v1", type = Nomenclature.class),
        @XmlElement(name = "div", namespace = "http://www.taxonx.org/schema/v1", type = Div.class),
        @XmlElement(name = "ref_group", namespace = "http://www.taxonx.org/schema/v1", type = RefGroup.class),
        @XmlElement(name = "pb", namespace = "http://www.taxonx.org/schema/v1", type = Pb.class),
        @XmlElement(name = "figure", namespace = "http://www.taxonx.org/schema/v1", type = Figure.class),
        @XmlElement(name = "treatment", namespace = "http://www.taxonx.org/schema/v1", type = Treatment.class)
    })
    protected List<Object> nomenclatureOrDivOrRefGroup;
    @XmlAttribute(name = "rank")
    protected String rank;
    @XmlAttribute(name = "other_rank")
    protected String otherRank;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "n")
    protected String n;

    /**
     * Gets the value of the taxonxHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonxHeader }
     *     
     */
    public TaxonxHeader getTaxonxHeader() {
        return taxonxHeader;
    }

    /**
     * Sets the value of the taxonxHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonxHeader }
     *     
     */
    public void setTaxonxHeader(TaxonxHeader value) {
        this.taxonxHeader = value;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the nomenclatureOrDivOrRefGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nomenclatureOrDivOrRefGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNomenclatureOrDivOrRefGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nomenclature }
     * {@link Div }
     * {@link RefGroup }
     * {@link Pb }
     * {@link Figure }
     * {@link Treatment }
     * 
     * 
     */
    public List<Object> getNomenclatureOrDivOrRefGroup() {
        if (nomenclatureOrDivOrRefGroup == null) {
            nomenclatureOrDivOrRefGroup = new ArrayList<Object>();
        }
        return this.nomenclatureOrDivOrRefGroup;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the otherRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRank() {
        return otherRank;
    }

    /**
     * Sets the value of the otherRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRank(String value) {
        this.otherRank = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN(String value) {
        this.n = value;
    }

}
