//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.26 at 06:10:52 PM MST 
//


package semanticMarkup.io.input.lib.newIPlant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}family_name" minOccurs="0"/>
 *         &lt;element ref="{}family_authority" minOccurs="0"/>
 *         &lt;element ref="{}subfamily_name" minOccurs="0"/>
 *         &lt;element ref="{}subfamily_authority" minOccurs="0"/>
 *         &lt;element ref="{}tribe_name" minOccurs="0"/>
 *         &lt;element ref="{}tribe_authority" minOccurs="0"/>
 *         &lt;element ref="{}subtribe_name" minOccurs="0"/>
 *         &lt;element ref="{}subtribe_authority" minOccurs="0"/>
 *         &lt;element ref="{}genus_name" minOccurs="0"/>
 *         &lt;element ref="{}genus_authority" minOccurs="0"/>
 *         &lt;element ref="{}subgenus_name" minOccurs="0"/>
 *         &lt;element ref="{}subgenus_authority" minOccurs="0"/>
 *         &lt;element ref="{}section_name" minOccurs="0"/>
 *         &lt;element ref="{}section_authority" minOccurs="0"/>
 *         &lt;element ref="{}subsection_name" minOccurs="0"/>
 *         &lt;element ref="{}subsection_authority" minOccurs="0"/>
 *         &lt;element ref="{}series_name" minOccurs="0"/>
 *         &lt;element ref="{}series_authority" minOccurs="0"/>
 *         &lt;element ref="{}species_name" minOccurs="0"/>
 *         &lt;element ref="{}species_authority" minOccurs="0"/>
 *         &lt;element ref="{}subspecies_name" minOccurs="0"/>
 *         &lt;element ref="{}subspecies_authority" minOccurs="0"/>
 *         &lt;element ref="{}variety_name" minOccurs="0"/>
 *         &lt;element ref="{}variety_authority" minOccurs="0"/>
 *         &lt;element ref="{}unranked_epithet_name" minOccurs="0"/>
 *         &lt;element ref="{}unranked_epithet_authority" minOccurs="0"/>
 *         &lt;element ref="{}other_info_on_name" minOccurs="0"/>
 *         &lt;element ref="{}place_of_publication" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "taxon_identification")
public class TaxonIdentification {

    @XmlElementRefs({
        @XmlElementRef(name = "genus_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tribe_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "section_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subtribe_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "series_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subspecies_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unranked_epithet_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "genus_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "section_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "variety_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "place_of_publication", type = PlaceOfPublication.class, required = false),
        @XmlElementRef(name = "subsection_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "family_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subfamily_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subsection_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unranked_epithet_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subgenus_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "series_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "species_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subspecies_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subfamily_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subgenus_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "species_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "family_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "other_info_on_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subtribe_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tribe_authority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "variety_name", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link PlaceOfPublication }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
