//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 03:48:51 PM MST 
//


package semanticMarkup.io.input.lib.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SubtribeName_QNAME = new QName("", "subtribe_name");
    private final static QName _SubtribeAuthority_QNAME = new QName("", "subtribe_authority");
    private final static QName _Discussion_QNAME = new QName("", "discussion");
    private final static QName _GlobalDistribution_QNAME = new QName("", "global_distribution");
    private final static QName _OtherInfo_QNAME = new QName("", "other_info");
    private final static QName _SubgenusName_QNAME = new QName("", "subgenus_name");
    private final static QName _FamilyAuthority_QNAME = new QName("", "family_authority");
    private final static QName _Determination_QNAME = new QName("", "determination");
    private final static QName _CommonName_QNAME = new QName("", "common_name");
    private final static QName _SectionName_QNAME = new QName("", "section_name");
    private final static QName _StatementId_QNAME = new QName("", "statement_id");
    private final static QName _NumberOfInfrataxa_QNAME = new QName("", "number_of_infrataxa");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _SpeciesName_QNAME = new QName("", "species_name");
    private final static QName _GenusName_QNAME = new QName("", "genus_name");
    private final static QName _FamilyName_QNAME = new QName("", "family_name");
    private final static QName _SubfamilyName_QNAME = new QName("", "subfamily_name");
    private final static QName _KeyHeading_QNAME = new QName("", "key_heading");
    private final static QName _SubspeciesName_QNAME = new QName("", "subspecies_name");
    private final static QName _VarietyAuthority_QNAME = new QName("", "variety_authority");
    private final static QName _PlaceInPublication_QNAME = new QName("", "place_in_publication");
    private final static QName _KeyAuthor_QNAME = new QName("", "key_author");
    private final static QName _VarietyName_QNAME = new QName("", "variety_name");
    private final static QName _SpeciesAuthority_QNAME = new QName("", "species_authority");
    private final static QName _Number_QNAME = new QName("", "number");
    private final static QName _TribeAuthority_QNAME = new QName("", "tribe_authority");
    private final static QName _Statement_QNAME = new QName("", "statement");
    private final static QName _Habitat_QNAME = new QName("", "habitat");
    private final static QName _Weedy_QNAME = new QName("", "weedy");
    private final static QName _PastName_QNAME = new QName("", "past_name");
    private final static QName _UsDistribution_QNAME = new QName("", "us_distribution");
    private final static QName _NextStatementId_QNAME = new QName("", "next_statement_id");
    private final static QName _PhenologyFruiting_QNAME = new QName("", "phenology_fruiting");
    private final static QName _GenusAuthority_QNAME = new QName("", "genus_authority");
    private final static QName _PublicationTitle_QNAME = new QName("", "publication_title");
    private final static QName _Illustrated_QNAME = new QName("", "illustrated");
    private final static QName _SectionAuthority_QNAME = new QName("", "section_authority");
    private final static QName _TribeName_QNAME = new QName("", "tribe_name");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _ReferenceDiscussion_QNAME = new QName("", "reference_discussion");
    private final static QName _CaDistribution_QNAME = new QName("", "ca_distribution");
    private final static QName _SubsectionName_QNAME = new QName("", "subsection_name");
    private final static QName _Conservation_QNAME = new QName("", "conservation");
    private final static QName _SubspeciesAuthority_QNAME = new QName("", "subspecies_authority");
    private final static QName _UnrankedEpithetName_QNAME = new QName("", "unranked_epithet_name");
    private final static QName _UnrankedEpithetAuthority_QNAME = new QName("", "unranked_epithet_authority");
    private final static QName _InvalidName_QNAME = new QName("", "invalid_name");
    private final static QName _KeyHead_QNAME = new QName("", "key_head");
    private final static QName _ConservedName_QNAME = new QName("", "conserved_name");
    private final static QName _SeriesAuthority_QNAME = new QName("", "series_authority");
    private final static QName _Etymology_QNAME = new QName("", "etymology");
    private final static QName _Elevation_QNAME = new QName("", "elevation");
    private final static QName _SeriesName_QNAME = new QName("", "series_name");
    private final static QName _Subspecies_QNAME = new QName("", "subspecies");
    private final static QName _Phenology_QNAME = new QName("", "phenology");
    private final static QName _SubsectionAuthority_QNAME = new QName("", "subsection_authority");
    private final static QName _Reference_QNAME = new QName("", "reference");
    private final static QName _KeyDiscussion_QNAME = new QName("", "key_discussion");
    private final static QName _SubfamilyAuthority_QNAME = new QName("", "subfamily_authority");
    private final static QName _Endemic_QNAME = new QName("", "endemic");
    private final static QName _SubgenusAuthority_QNAME = new QName("", "subgenus_authority");
    private final static QName _Introduced_QNAME = new QName("", "introduced");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyStatement }
     * 
     */
    public KeyStatement createKeyStatement() {
        return new KeyStatement();
    }

    /**
     * Create an instance of {@link Treatment }
     * 
     */
    public Treatment createTreatment() {
        return new Treatment();
    }

    /**
     * Create an instance of {@link TaxonIdentification }
     * 
     */
    public TaxonIdentification createTaxonIdentification() {
        return new TaxonIdentification();
    }

    /**
     * Create an instance of {@link PlaceOfPublication }
     * 
     */
    public PlaceOfPublication createPlaceOfPublication() {
        return new PlaceOfPublication();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subtribe_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSubtribeName(String value) {
        return new JAXBElement<String>(_SubtribeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subtribe_authority")
    public JAXBElement<String> createSubtribeAuthority(String value) {
        return new JAXBElement<String>(_SubtribeAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "discussion")
    public JAXBElement<String> createDiscussion(String value) {
        return new JAXBElement<String>(_Discussion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "global_distribution")
    public JAXBElement<String> createGlobalDistribution(String value) {
        return new JAXBElement<String>(_GlobalDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "other_info")
    public JAXBElement<String> createOtherInfo(String value) {
        return new JAXBElement<String>(_OtherInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subgenus_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSubgenusName(String value) {
        return new JAXBElement<String>(_SubgenusName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "family_authority")
    public JAXBElement<String> createFamilyAuthority(String value) {
        return new JAXBElement<String>(_FamilyAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "determination")
    public JAXBElement<String> createDetermination(String value) {
        return new JAXBElement<String>(_Determination_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "common_name")
    public JAXBElement<String> createCommonName(String value) {
        return new JAXBElement<String>(_CommonName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSectionName(String value) {
        return new JAXBElement<String>(_SectionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statement_id")
    public JAXBElement<String> createStatementId(String value) {
        return new JAXBElement<String>(_StatementId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_infrataxa")
    public JAXBElement<String> createNumberOfInfrataxa(String value) {
        return new JAXBElement<String>(_NumberOfInfrataxa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "species_name")
    public JAXBElement<String> createSpeciesName(String value) {
        return new JAXBElement<String>(_SpeciesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genus_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGenusName(String value) {
        return new JAXBElement<String>(_GenusName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "family_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFamilyName(String value) {
        return new JAXBElement<String>(_FamilyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subfamily_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSubfamilyName(String value) {
        return new JAXBElement<String>(_SubfamilyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_heading")
    public JAXBElement<String> createKeyHeading(String value) {
        return new JAXBElement<String>(_KeyHeading_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subspecies_name")
    public JAXBElement<String> createSubspeciesName(String value) {
        return new JAXBElement<String>(_SubspeciesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variety_authority")
    public JAXBElement<String> createVarietyAuthority(String value) {
        return new JAXBElement<String>(_VarietyAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "place_in_publication")
    public JAXBElement<String> createPlaceInPublication(String value) {
        return new JAXBElement<String>(_PlaceInPublication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_author")
    public JAXBElement<String> createKeyAuthor(String value) {
        return new JAXBElement<String>(_KeyAuthor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variety_name")
    public JAXBElement<String> createVarietyName(String value) {
        return new JAXBElement<String>(_VarietyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "species_authority")
    public JAXBElement<String> createSpeciesAuthority(String value) {
        return new JAXBElement<String>(_SpeciesAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tribe_authority")
    public JAXBElement<String> createTribeAuthority(String value) {
        return new JAXBElement<String>(_TribeAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statement")
    public JAXBElement<String> createStatement(String value) {
        return new JAXBElement<String>(_Statement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "habitat")
    public JAXBElement<String> createHabitat(String value) {
        return new JAXBElement<String>(_Habitat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "weedy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWeedy(String value) {
        return new JAXBElement<String>(_Weedy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "past_name")
    public JAXBElement<String> createPastName(String value) {
        return new JAXBElement<String>(_PastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "us_distribution")
    public JAXBElement<String> createUsDistribution(String value) {
        return new JAXBElement<String>(_UsDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "next_statement_id")
    public JAXBElement<String> createNextStatementId(String value) {
        return new JAXBElement<String>(_NextStatementId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phenology_fruiting")
    public JAXBElement<String> createPhenologyFruiting(String value) {
        return new JAXBElement<String>(_PhenologyFruiting_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genus_authority")
    public JAXBElement<String> createGenusAuthority(String value) {
        return new JAXBElement<String>(_GenusAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publication_title")
    public JAXBElement<String> createPublicationTitle(String value) {
        return new JAXBElement<String>(_PublicationTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "illustrated")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIllustrated(String value) {
        return new JAXBElement<String>(_Illustrated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section_authority")
    public JAXBElement<String> createSectionAuthority(String value) {
        return new JAXBElement<String>(_SectionAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tribe_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTribeName(String value) {
        return new JAXBElement<String>(_TribeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reference_discussion")
    public JAXBElement<String> createReferenceDiscussion(String value) {
        return new JAXBElement<String>(_ReferenceDiscussion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ca_distribution")
    public JAXBElement<String> createCaDistribution(String value) {
        return new JAXBElement<String>(_CaDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subsection_name")
    public JAXBElement<String> createSubsectionName(String value) {
        return new JAXBElement<String>(_SubsectionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "conservation")
    public JAXBElement<String> createConservation(String value) {
        return new JAXBElement<String>(_Conservation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subspecies_authority")
    public JAXBElement<String> createSubspeciesAuthority(String value) {
        return new JAXBElement<String>(_SubspeciesAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unranked_epithet_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnrankedEpithetName(String value) {
        return new JAXBElement<String>(_UnrankedEpithetName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unranked_epithet_authority")
    public JAXBElement<String> createUnrankedEpithetAuthority(String value) {
        return new JAXBElement<String>(_UnrankedEpithetAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "invalid_name")
    public JAXBElement<String> createInvalidName(String value) {
        return new JAXBElement<String>(_InvalidName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_head")
    public JAXBElement<String> createKeyHead(String value) {
        return new JAXBElement<String>(_KeyHead_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "conserved_name")
    public JAXBElement<String> createConservedName(String value) {
        return new JAXBElement<String>(_ConservedName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "series_authority")
    public JAXBElement<String> createSeriesAuthority(String value) {
        return new JAXBElement<String>(_SeriesAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "etymology")
    public JAXBElement<String> createEtymology(String value) {
        return new JAXBElement<String>(_Etymology_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elevation")
    public JAXBElement<String> createElevation(String value) {
        return new JAXBElement<String>(_Elevation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "series_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSeriesName(String value) {
        return new JAXBElement<String>(_SeriesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subspecies")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSubspecies(String value) {
        return new JAXBElement<String>(_Subspecies_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phenology")
    public JAXBElement<String> createPhenology(String value) {
        return new JAXBElement<String>(_Phenology_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subsection_authority")
    public JAXBElement<String> createSubsectionAuthority(String value) {
        return new JAXBElement<String>(_SubsectionAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reference")
    public JAXBElement<String> createReference(String value) {
        return new JAXBElement<String>(_Reference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_discussion")
    public JAXBElement<String> createKeyDiscussion(String value) {
        return new JAXBElement<String>(_KeyDiscussion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subfamily_authority")
    public JAXBElement<String> createSubfamilyAuthority(String value) {
        return new JAXBElement<String>(_SubfamilyAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "endemic")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEndemic(String value) {
        return new JAXBElement<String>(_Endemic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subgenus_authority")
    public JAXBElement<String> createSubgenusAuthority(String value) {
        return new JAXBElement<String>(_SubgenusAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "introduced")
    public JAXBElement<String> createIntroduced(String value) {
        return new JAXBElement<String>(_Introduced_QNAME, String.class, null, value);
    }

}
