//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 03:50:25 PM MST 
//


package semanticMarkup.io.output.lib.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}number" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}TaxonIdentification"/>
 *           &lt;element ref="{}etymology"/>
 *           &lt;element ref="{}other_info"/>
 *           &lt;element ref="{}conserved_name"/>
 *           &lt;element ref="{}common_name"/>
 *           &lt;element ref="{}invalid_name"/>
 *           &lt;element ref="{}past_name"/>
 *           &lt;element ref="{}author"/>
 *           &lt;element ref="{}conservation"/>
 *           &lt;element ref="{}weedy"/>
 *           &lt;element ref="{}endemic"/>
 *           &lt;element ref="{}illustrated"/>
 *           &lt;element ref="{}description"/>
 *           &lt;element ref="{}phenology"/>
 *           &lt;element ref="{}phenology_fruiting"/>
 *           &lt;element ref="{}habitat"/>
 *           &lt;element ref="{}elevation"/>
 *           &lt;element ref="{}number_of_infrataxa"/>
 *           &lt;element ref="{}introduced"/>
 *           &lt;element ref="{}ca_distribution"/>
 *           &lt;element ref="{}us_distribution"/>
 *           &lt;element ref="{}global_distribution"/>
 *           &lt;element ref="{}discussion"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}references"/>
 *           &lt;element ref="{}key"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "taxonIdentificationOrEtymologyOrOtherInfo",
    "referencesOrKey"
})
@XmlRootElement(name = "treatment")
public class Treatment {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String number;
    @XmlElementRefs({
        @XmlElementRef(name = "phenology_fruiting", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "invalid_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "illustrated", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "phenology", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "weedy", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "common_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", type = Description.class, required = false),
        @XmlElementRef(name = "global_distribution", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "conservation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "habitat", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "other_info", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "number_of_infrataxa", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "elevation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "author", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "discussion", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TaxonIdentification", type = TaxonIdentification.class, required = false),
        @XmlElementRef(name = "conserved_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "etymology", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ca_distribution", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "us_distribution", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "past_name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "endemic", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "introduced", type = JAXBElement.class, required = false)
    })
    protected List<Object> taxonIdentificationOrEtymologyOrOtherInfo;
    @XmlElements({
        @XmlElement(name = "references", type = References.class),
        @XmlElement(name = "key", type = Key.class)
    })
    protected List<Object> referencesOrKey;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the taxonIdentificationOrEtymologyOrOtherInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonIdentificationOrEtymologyOrOtherInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonIdentificationOrEtymologyOrOtherInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Description }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link TaxonIdentification }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getTaxonIdentificationOrEtymologyOrOtherInfo() {
        if (taxonIdentificationOrEtymologyOrOtherInfo == null) {
            taxonIdentificationOrEtymologyOrOtherInfo = new ArrayList<Object>();
        }
        return this.taxonIdentificationOrEtymologyOrOtherInfo;
    }

    /**
     * Gets the value of the referencesOrKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencesOrKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencesOrKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link References }
     * {@link Key }
     * 
     * 
     */
    public List<Object> getReferencesOrKey() {
        if (referencesOrKey == null) {
            referencesOrKey = new ArrayList<Object>();
        }
        return this.referencesOrKey;
    }

}
