//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 03:40:16 PM MST 
//


package semanticMarkup.io.input.lib.iplant;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}meta"/>
 *         &lt;element ref="{}TaxonIdentification"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}discussion" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "meta",
    "taxonIdentification",
    "description",
    "discussion"
})
@XmlRootElement(name = "treatment")
public class Treatment {

    @XmlElement(required = true)
    protected Meta meta;
    @XmlElement(name = "TaxonIdentification", required = true)
    protected TaxonIdentification taxonIdentification;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected List<String> discussion;

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the taxonIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonIdentification }
     *     
     */
    public TaxonIdentification getTaxonIdentification() {
        return taxonIdentification;
    }

    /**
     * Sets the value of the taxonIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonIdentification }
     *     
     */
    public void setTaxonIdentification(TaxonIdentification value) {
        this.taxonIdentification = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the discussion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discussion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscussion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDiscussion() {
        if (discussion == null) {
            discussion = new ArrayList<String>();
        }
        return this.discussion;
    }

}
